name: Craftify
options:
  bundleIdPrefix: dev.korchasa
  deploymentTarget:
    iOS: 16.0
configs:
  Debug: debug
  Release: release
settings:
  base:
    DEVELOPMENT_TEAM: 78M3ZDR5UH
    SWIFT_VERSION: 5.9
    CODE_SIGN_STYLE: Automatic
    ENABLE_BITCODE: NO
    SWIFT_OPTIMIZATION_LEVEL: '-Onone'
    CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: YES
    SWIFT_TREAT_WARNINGS_AS_ERRORS: YES
  debug:
    OTHER_LDFLAGS: "$(inherited) -ObjC"
  release:
    OTHER_LDFLAGS: "$(inherited) -dead_strip -ObjC"
    SWIFT_OPTIMIZATION_LEVEL: '-O'
targets:
  MainApp:
    type: application
    platform: iOS
    sources:
      - path: src/Common/Sources
        recursive: true
      - path: src/MainApp/Sources
        recursive: true
      - path: src/MainApp/Resources/Generated/Strings.swift
    dependencies:
      - package: SwiftSoup
      - target: ShareExtension
    resources:
      - path: src/MainApp/Resources
        excludes:
          - Generated/Strings.swift
    appIcon: AppIcon
    info:
      path: src/MainApp/Config/Info.plist
      properties:
        CFBundleDisplayName: Craftify
        CFBundleIconName: AppIcon
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiresFullScreen: true
    entitlements:
      path: src/MainApp/Config/Craftify.entitlements
      properties:
        com.apple.security.application-groups:
          - group.dev.korchasa.Craftify
        keychain-access-groups:
          - 78M3ZDR5UH.group.dev.korchasa.Craftify
    settings:
      base:
        CODE_SIGN_STYLE: Manual
        PRODUCT_BUNDLE_IDENTIFIER: dev.korchasa.Craftify
        APP_GROUPS: group.dev.korchasa.Craftify
        KEYCHAIN_ACCESS_GROUPS: 78M3ZDR5UH.*
        PROVISIONING_PROFILE_SPECIFIER: "Craftify MainApp"
    embedAppExtensions:
      - ShareExtension
    embed:
      - target: ShareExtension
  MainAppUnitTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: src/Common/Sources
        recursive: true
      - path: src/MainApp/UnitTests
      - path: src/MainApp/Sources
        recursive: true
      - path: src/MainApp/Resources/Generated/Strings.swift
    dependencies:
      - target: MainApp
      - package: CwlPreconditionTesting
      - package: CwlCatchException
      - package: ViewInspector
      - package: SwiftSoup
      - sdk: XCTest.framework
    testTarget: true
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        ENABLE_TESTING_SEARCH_PATHS: YES
        SDKROOT: iphonesimulator
        OTHER_LDFLAGS:
          - "-weak_framework"
          - "XCTest"
          - "-weak-lXCTestSwiftSupport"
  ShareExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: src/Common/Sources
        recursive: true
      - path: src/ShareExtension/Sources
        recursive: true
      - path: src/ShareExtension/Resources/Generated/Strings.swift
    dependencies:
      - package: SwiftSoup
    resources:
      - path: src/ShareExtension/Resources
      - path: src/ShareExtension/Resources/Assets.xcassets
      - path: src/Common/Resources/en.lproj
      - path: src/Common/Resources/ru.lproj
    appIcon: AppIcon
    info:
      path: src/ShareExtension/Config/Info.plist
      properties:
        CFBundleIconName: AppIcon
        CFBundleDisplayName: Craftify Share
        NSExtension:
          NSExtensionPointIdentifier: com.apple.share-services
          NSExtensionAttributes:
            NSExtensionActivationRule:
              NSExtensionActivationSupportsText: true
              NSExtensionActivationSupportsWebURLWithMaxCount: 1
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ShareExtensionViewController
    entitlements:
      path: src/ShareExtension/Config/ShareExtension.entitlements
      properties:
        com.apple.security.application-groups:
          - group.dev.korchasa.Craftify
        keychain-access-groups:
          - 78M3ZDR5UH.group.dev.korchasa.Craftify
    settings:
      base:
        CODE_SIGN_STYLE: Manual
        PRODUCT_BUNDLE_IDENTIFIER: dev.korchasa.Craftify.ShareExtension
        APP_GROUPS: group.dev.korchasa.Craftify
        KEYCHAIN_ACCESS_GROUPS: 78M3ZDR5UH.*
        PROVISIONING_PROFILE_SPECIFIER: "Craftify Share Extension"
        ENABLE_TESTING_SEARCH_PATHS: NO
  ShareExtensionUnitTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: src/Common/Sources
        recursive: true
      - path: src/ShareExtension/UnitTests
      - path: src/ShareExtension/Sources
        recursive: true
      - path: src/ShareExtension/Resources/Generated/Strings.swift
    dependencies:
      - target: ShareExtension
      - package: CwlPreconditionTesting
      - package: CwlCatchException
      - package: ViewInspector
      - package: SwiftSoup
    testTarget: true
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        ENABLE_TESTING_SEARCH_PATHS: YES
        SDKROOT: iphonesimulator
        OTHER_LDFLAGS:
          - "-weak_framework"
          - "XCTest"
          - "-weak-lXCTestSwiftSupport"
  CommonUnitTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: src/Common/Sources
        recursive: true
      - path: src/Common/UnitTests
      - path: src/MainApp/Resources/Generated/Strings.swift
      - path: src/MainApp/Sources/ViewConstants.swift
    dependencies:
      - package: CwlPreconditionTesting
      - package: CwlCatchException
      - package: SwiftSoup
      - sdk: XCTest.framework
    testTarget: true
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        ENABLE_TESTING_SEARCH_PATHS: YES
        SDKROOT: iphonesimulator
        OTHER_LDFLAGS:
          - "-weak_framework"
          - "XCTest"
          - "-weak-lXCTestSwiftSupport"
packages:
  CwlPreconditionTesting:
    url: https://github.com/mattgallagher/CwlPreconditionTesting.git
    from: 2.2.2
  CwlCatchException:
    url: https://github.com/mattgallagher/CwlCatchException.git
    from: 2.2.1
  SwiftSoup:
    url: https://github.com/scinfu/SwiftSoup.git
    from: 2.4.3
  ViewInspector:
    url: https://github.com/nalexn/ViewInspector.git
    from: 0.9.0

schemes:
  AllTests:
    build:
      targets:
        MainApp: all
        ShareExtension: all
    test:
      targets:
        - name: MainAppUnitTests
        - name: ShareExtensionUnitTests
        - name: CommonUnitTests
  MainApp:
    build:
      targets:
        MainApp: all
        ShareExtension: all
  ShareExtension:
    build:
      targets:
        ShareExtension: all
  ShareExtensionSizeReport:
    build:
      targets:
        ShareExtension: all
    run:
      config: Release
configFiles:
  Debug: Configs/Debug.xcconfig
  Release: Configs/Release.xcconfig