name: Craftify
options:
  bundleIdPrefix: dev.korchasa
  deploymentTarget:
    iOS: 16.0
configs:
  Debug: debug
  Release: release
settings:
  base:
    DEVELOPMENT_TEAM: 78M3ZDR5UH
    SWIFT_VERSION: 5.9
    CODE_SIGN_STYLE: Automatic
    ENABLE_BITCODE: NO
    SWIFT_OPTIMIZATION_LEVEL: '-Onone'
    CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: YES
    SWIFT_TREAT_WARNINGS_AS_ERRORS: YES
  debug:
    OTHER_LDFLAGS: "$(inherited) -ObjC"
  release:
    OTHER_LDFLAGS: "$(inherited) -dead_strip -ObjC"
    SWIFT_OPTIMIZATION_LEVEL: '-O'
targets:
  MainApp:
    type: application
    platform: iOS
    sources:
      - path: src/MainApp/Sources
      - path: src/Common/Generated/Strings.swift
      - path: src/Common/Sources/ColorPaletteConstants.swift
    resources:
      - path: src/MainApp/Resources
        excludes:
          - Generated/Strings.swift
    info:
      path: src/MainApp/Config/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiresFullScreen: true
    entitlements:
      path: src/MainApp/Config/Craftify.entitlements
      properties:
        com.apple.security.application-groups:
          - group.dev.korchasa.Craftify
        keychain-access-groups:
          - 78M3ZDR5UH.group.dev.korchasa.Craftify
    settings:
      base:
        CODE_SIGN_STYLE: Manual
        PRODUCT_BUNDLE_IDENTIFIER: dev.korchasa.Craftify
        APP_GROUPS: group.dev.korchasa.Craftify
        KEYCHAIN_ACCESS_GROUPS: 78M3ZDR5UH.*
        PROVISIONING_PROFILE_SPECIFIER: "Craftify MainApp"
    dependencies:
      - target: Common
      - package: NewRelic
      - target: ShareExtension
    embedAppExtensions:
      - ShareExtension
  MainAppUnitTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: src/MainApp/UnitTests
      - path: src/MainApp/Sources
      - path: src/Common/Generated/Strings.swift
    dependencies:
      - target: MainApp
      - package: Nimble
      - package: CwlPreconditionTesting
      - package: CwlCatchException
    testTarget: true
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
  MainAppE2ETests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: src/MainApp/E2ETests
      - path: src/MainApp/Sources
      - path: src/Common/Generated/Strings.swift
    dependencies:
      - target: MainApp
      - package: Nimble
      - package: CwlPreconditionTesting
      - package: CwlCatchException
    testTarget: true
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
  ShareExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: src/ShareExtension/Sources
      - path: src/Common/Generated/Strings.swift
    resources:
      - path: src/ShareExtension/Resources
    info:
      path: src/ShareExtension/Config/Info.plist
      properties:
        CFBundleDisplayName: Craftify Share
        NSExtension:
          NSExtensionPointIdentifier: com.apple.share-services
          NSExtensionAttributes:
            NSExtensionActivationRule: |
              SUBQUERY (
                extensionItems,
                $extensionItem,
                SUBQUERY (
                  $extensionItem.attachments,
                  $attachment,
                  ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.text" ||
                  ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.url"
                ).@count > 0
              ).@count > 0
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ShareExtensionViewController
    dependencies:
      - target: Common
    entitlements:
      path: src/ShareExtension/Config/ShareExtension.entitlements
      properties:
        com.apple.security.application-groups:
          - group.dev.korchasa.Craftify
        keychain-access-groups:
          - 78M3ZDR5UH.group.dev.korchasa.Craftify
    settings:
      base:
        CODE_SIGN_STYLE: Manual
        PRODUCT_BUNDLE_IDENTIFIER: dev.korchasa.Craftify.ShareExtension
        APP_GROUPS: group.dev.korchasa.Craftify
        KEYCHAIN_ACCESS_GROUPS: 78M3ZDR5UH.*
        PROVISIONING_PROFILE_SPECIFIER: "Craftify Share Extension"
  ShareExtensionUnitTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: src/ShareExtension/UnitTests
      - path: src/ShareExtension/Sources
      - path: src/Common/Generated/Strings.swift
    dependencies:
      - target: ShareExtension
      - package: Nimble
      - package: CwlPreconditionTesting
      - package: CwlCatchException
    testTarget: true
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
  ShareExtensionE2ETests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: src/ShareExtension/E2ETests
      - path: src/ShareExtension/Sources
      - path: src/Common/Generated/Strings.swift
    dependencies:
      - target: ShareExtension
      - package: Nimble
      - package: CwlPreconditionTesting
      - package: CwlCatchException
    testTarget: true
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
  Common:
    type: framework
    platform: iOS
    sources:
      - path: src/Common/Sources
      - path: src/Common/Generated/Strings.swift
    resources: []
    info:
      path: src/Common/Config/Info.plist
    settings:
      base:
        ENABLE_MODULE_VERIFIER: YES
        MODULE_VERIFIER_SUPPORTED_LANGUAGE_STANDARDS: "gnu11 gnu++14"
        DYLIB_COMPATIBILITY_VERSION: 1
        DYLIB_CURRENT_VERSION: 1
        DYLIB_INSTALL_NAME_BASE: "@rpath"
        INSTALL_PATH: "$(LOCAL_LIBRARY_DIR)/Frameworks"
        SKIP_INSTALL: YES
        VERSIONING_SYSTEM: "apple-generic"
        ENABLE_USER_SCRIPT_SANDBOXING: YES
        ENABLE_STRICT_OBJC_MSGSEND: YES
        GCC_C_LANGUAGE_STANDARD: gnu11
        GCC_NO_COMMON_BLOCKS: YES
        MTL_FAST_MATH: YES
        ENABLE_TESTABILITY: YES
        SDKROOT: iphoneos
        PRODUCT_NAME: "$(TARGET_NAME)"
        PRODUCT_BUNDLE_IDENTIFIER: dev.korchasa.Common
        INFOPLIST_FILE: src/Common/Config/Info.plist
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
        SWIFT_VERSION: 5.9
      debug:
        GCC_DYNAMIC_NO_PIC: NO
        SWIFT_OPTIMIZATION_LEVEL: '-Onone'
      release:
        SWIFT_OPTIMIZATION_LEVEL: '-O'
  CommonUnitTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: src/Common/UnitTests
      - path: src/Common/Sources
    dependencies:
      - target: Common
      - package: Nimble
      - package: CwlPreconditionTesting
      - package: CwlCatchException
    testTarget: true
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
  CommonE2ETests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: src/Common/E2ETests
      - path: src/Common/Sources
    dependencies:
      - target: Common
      - package: Nimble
      - package: CwlPreconditionTesting
      - package: CwlCatchException
    testTarget: true
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
packages:
  Nimble:
    url: https://github.com/Quick/Nimble.git
    from: 12.0.0
  CwlPreconditionTesting:
    url: https://github.com/mattgallagher/CwlPreconditionTesting.git
    from: 2.2.2
  CwlCatchException:
    url: https://github.com/mattgallagher/CwlCatchException.git
    from: 2.2.1
  NewRelic:
    url: https://github.com/newrelic/newrelic-ios-agent-spm
    from: 7.5.5

testPlans:
  Unit:
    name: Unit Tests
    description: "Запуск всех unit-тестов"
    testTargets:
      - MainAppUnitTests
      - ShareExtensionUnitTests
      - CommonUnitTests
  E2E-Common:
    name: "E2E Common Tests"
    description: "Запуск E2E тестов для модуля Common"
    testTargets:
      - CommonE2ETests
  E2E-MainApp:
    name: "E2E MainApp Tests"
    description: "Запуск E2E тестов для MainApp"
    testTargets:
      - MainAppE2ETests
  E2E-ShareExtension:
    name: "E2E ShareExtension Tests"
    description: "Запуск E2E тестов для ShareExtension"
    testTargets:
      - ShareExtensionE2ETests

schemes:
  MainApp:
    build:
      targets:
        MainApp: all
        ShareExtension: all
  MainAppUnitTests:
    build:
      targets:
        MainApp: all
    test:
      testPlans:
        - Unit
      targets:
        - name: MainAppUnitTests
  MainAppE2ETests:
    build:
      targets:
        MainApp: all
    test:
      testPlans:
        - E2E-MainApp
      targets:
        - name: MainAppE2ETests
  ShareExtension:
    build:
      targets:
        ShareExtension: all
  ShareExtensionUnitTests:
    build:
      targets:
        ShareExtension: all
    test:
      testPlans:
        - Unit
      targets:
        - name: ShareExtensionUnitTests
  ShareExtensionE2ETests:
    build:
      targets:
        ShareExtension: all
    test:
      testPlans:
        - E2E-ShareExtension
      targets:
        - name: ShareExtensionE2ETests
  CommonUnitTests:
    build:
      targets:
        Common: all
    test:
      testPlans:
        - Unit
      targets:
        - name: CommonUnitTests
  CommonE2ETests:
    build:
      targets:
        Common: all
    test:
      testPlans:
        - E2E-Common
      targets:
        - name: CommonE2ETests
  ShareExtensionSizeReport:
    build:
      targets:
        ShareExtension: all
    run:
      config: Release
configFiles:
  Debug: Configs/Debug.xcconfig
  Release: Configs/Release.xcconfig