name: Craftify
options:
  bundleIdPrefix: dev.korchasa
  deploymentTarget:
    iOS: 16.0
configs:
  Debug: debug
  Release: release
settings:
  base:
    DEVELOPMENT_TEAM: YOUR_TEAM_ID
    SWIFT_VERSION: 5.0
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
    ENABLE_BITCODE: NO
    SWIFT_OPTIMIZATION_LEVEL: '-Onone'
targets:
  MainApp:
    type: application
    platform: iOS
    sources:
      - path: src/MainApp/Sources
      - path: src/MainApp/Resources/Generated/Strings.swift
    resources:
      - path: src/MainApp/Resources
    info:
      path: src/MainApp/Config/Info.plist
    entitlements:
      path: src/MainApp/Config/Craftify.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.korchasa.Craftify
        APP_GROUPS: group.dev.korchasa.Craftify
        KEYCHAIN_ACCESS_GROUPS: group.dev.korchasa.Craftify
        SWIFT_VERSION: 5.0
    dependencies:
      - target: CraftifyShared
  MainAppUnitTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: src/MainApp/UnitTests
      - path: src/MainApp/Sources
      - path: src/MainApp/Resources/Generated/Strings.swift
    dependencies:
      - target: MainApp
      - package: Nimble
      - package: CwlPreconditionTesting
      - package: CwlCatchException
    info:
      path: src/MainApp/Config/Info.plist
    testTarget: true
    settings:
      base:
        SWIFT_VERSION: 5.0
  MainAppE2ETests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: src/MainApp/E2ETests
      - path: src/MainApp/Sources
      - path: src/MainApp/Resources/Generated/Strings.swift
    dependencies:
      - target: MainApp
      - package: Nimble
      - package: CwlPreconditionTesting
      - package: CwlCatchException
    info:
      path: src/MainApp/Config/Info.plist
    testTarget: true
    settings:
      base:
        SWIFT_VERSION: 5.0
  ShareExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: src/ShareExtension/Sources
    resources:
      - path: src/ShareExtension/Resources
    info:
      path: src/ShareExtension/Config/Info.plist
    entitlements:
      path: src/ShareExtension/Config/ShareExtension.entitlements
    dependencies:
      - target: CraftifyShared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.korchasa.Craftify.ShareExtension
        APP_GROUPS: group.dev.korchasa.Craftify
        KEYCHAIN_ACCESS_GROUPS: group.dev.korchasa.Craftify
        SWIFT_VERSION: 5.0
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "Apple Development: korchasa@icloud.com (2P55B82U54)"
        PROVISIONING_PROFILE_SPECIFIER: "09d74528-408d-43f1-96bd-259a04739802"
        DEVELOPMENT_TEAM: 78M3ZDR5UH
  ShareExtensionUnitTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: src/ShareExtension/UnitTests
      - path: src/ShareExtension/Sources
    dependencies:
      - target: ShareExtension
      - package: Nimble
      - package: CwlPreconditionTesting
      - package: CwlCatchException
    info:
      path: src/ShareExtension/Config/Info.plist
    testTarget: true
    settings:
      base:
        SWIFT_VERSION: 5.0
  ShareExtensionE2ETests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: src/ShareExtension/E2ETests
      - path: src/ShareExtension/Sources
    dependencies:
      - target: ShareExtension
      - package: Nimble
      - package: CwlPreconditionTesting
      - package: CwlCatchException
    info:
      path: src/ShareExtension/Config/Info.plist
    testTarget: true
    settings:
      base:
        SWIFT_VERSION: 5.0
  CraftifyShared:
    type: framework
    platform: iOS
    sources:
      - path: src/CraftifyShared/Sources
      - path: src/CraftifyShared/Generated/Strings.swift
    resources: []
    info:
      path: src/CraftifyShared/Config/Info.plist
    settings:
      base:
        SWIFT_VERSION: 5.0
        ENABLE_TESTABILITY: YES
  CraftifySharedUnitTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: src/CraftifyShared/UnitTests
      - path: src/CraftifyShared/Sources
    dependencies:
      - target: CraftifyShared
      - package: Nimble
      - package: CwlPreconditionTesting
      - package: CwlCatchException
    info:
      path: src/CraftifyShared/Config/Info.plist
    testTarget: true
    settings:
      base:
        SWIFT_VERSION: 5.0
  CraftifySharedE2ETests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: src/CraftifyShared/E2ETests
      - path: src/CraftifyShared/Sources
    dependencies:
      - target: CraftifyShared
      - package: Nimble
      - package: CwlPreconditionTesting
      - package: CwlCatchException
    info:
      path: src/CraftifyShared/Config/Info.plist
    testTarget: true
    settings:
      base:
        SWIFT_VERSION: 5.0
packages:
  Nimble:
    url: https://github.com/Quick/Nimble.git
    from: 12.0.0
  CwlPreconditionTesting:
    url: https://github.com/mattgallagher/CwlPreconditionTesting.git
    from: 2.2.2
  CwlCatchException:
    url: https://github.com/mattgallagher/CwlCatchException.git
    from: 2.2.1
schemes:
  MainApp:
    build:
      targets:
        MainApp: all
  MainAppUnitTests:
    build:
      targets:
        MainApp: all
    test:
      targets:
        - name: MainAppUnitTests
  MainAppE2ETests:
    build:
      targets:
        MainApp: all
    test:
      targets:
        - name: MainAppE2ETests
  ShareExtensionUnitTests:
    build:
      targets:
        ShareExtension: all
    test:
      targets:
        - name: ShareExtensionUnitTests
  ShareExtensionE2ETests:
    build:
      targets:
        ShareExtension: all
    test:
      targets:
        - name: ShareExtensionE2ETests
  CraftifySharedUnitTests:
    build:
      targets:
        CraftifyShared: all
    test:
      targets:
        - name: CraftifySharedUnitTests
  CraftifySharedE2ETests:
    build:
      targets:
        CraftifyShared: all
    test:
      targets:
        - name: CraftifySharedE2ETests