/// Contains the list of all supported languages for Craftify operations.
public enum SupportedLanguages {
    /// All supported languages (code, native name, English name)
    public static let all: [SupportedLanguage] = [
        SupportedLanguage(code: "aa", name: "Afaraf", englishName: "Afar"),
        SupportedLanguage(code: "ab", name: "Аҧсуа", englishName: "Abkhazian"),
        SupportedLanguage(code: "ae", name: "avesta", englishName: "Avestan"),
        SupportedLanguage(code: "af", name: "Afrikaans", englishName: "Afrikaans"),
        SupportedLanguage(code: "ak", name: "Akan", englishName: "Akan"),
        SupportedLanguage(code: "am", name: "አማርኛ", englishName: "Amharic"),
        SupportedLanguage(code: "an", name: "Aragonés", englishName: "Aragonese"),
        SupportedLanguage(code: "ar", name: "العربية", englishName: "Arabic"),
        SupportedLanguage(code: "as", name: "অসমীয়া", englishName: "Assamese"),
        SupportedLanguage(code: "av", name: "авар мацӀ", englishName: "Avaric"),
        SupportedLanguage(code: "ay", name: "aymar aru", englishName: "Aymara"),
        SupportedLanguage(code: "az", name: "azərbaycan dili", englishName: "Azerbaijani"),
        SupportedLanguage(code: "ba", name: "башҡорт теле", englishName: "Bashkir"),
        SupportedLanguage(code: "be", name: "Беларуская", englishName: "Belarusian"),
        SupportedLanguage(code: "bg", name: "български език", englishName: "Bulgarian"),
        SupportedLanguage(code: "bh", name: "भोजपुरी", englishName: "Bihari languages"),
        SupportedLanguage(code: "bi", name: "Bislama", englishName: "Bislama"),
        SupportedLanguage(code: "bm", name: "bamanankan", englishName: "Bambara"),
        SupportedLanguage(code: "bn", name: "বাংলা", englishName: "Bengali"),
        SupportedLanguage(code: "bo", name: "བོད་ཡིག", englishName: "Tibetan Standard, Tibetan, Central"),
        SupportedLanguage(code: "br", name: "brezhoneg", englishName: "Breton"),
        SupportedLanguage(code: "bs", name: "bosanski jezik", englishName: "Bosnian"),
        SupportedLanguage(code: "ca", name: "Català", englishName: "Catalan; Valencian"),
        SupportedLanguage(code: "ce", name: "нохчийн мотт", englishName: "Chechen"),
        SupportedLanguage(code: "ch", name: "Chamoru", englishName: "Chamorro"),
        SupportedLanguage(code: "co", name: "corsu", englishName: "Corsican"),
        SupportedLanguage(code: "cr", name: "ᓀᐦᐃᔭᐍᐏᐣ", englishName: "Cree"),
        SupportedLanguage(code: "cs", name: "čeština", englishName: "Czech"),
        SupportedLanguage(code: "cv", name: "чӑваш чӗлхи", englishName: "Chuvash"),
        SupportedLanguage(code: "cy", name: "Cymraeg", englishName: "Welsh"),
        SupportedLanguage(code: "da", name: "dansk", englishName: "Danish"),
        SupportedLanguage(code: "de", name: "Deutsch", englishName: "German"),
        SupportedLanguage(code: "dtr", name: "Dothraki", englishName: "Dothraki"),
        SupportedLanguage(code: "dv", name: "ދިވެހި", englishName: "Divehi; Dhivehi; Maldivian"),
        SupportedLanguage(code: "ee", name: "Eʋegbe", englishName: "Ewe"),
        SupportedLanguage(code: "el", name: "Ελληνικά", englishName: "Greek, Modern"),
        SupportedLanguage(code: "en", name: "English", englishName: "English"),
        SupportedLanguage(code: "eo", name: "Esperanto", englishName: "Esperanto"),
        SupportedLanguage(code: "es", name: "español", englishName: "Spanish; Castilian"),
        SupportedLanguage(code: "et", name: "eesti", englishName: "Estonian"),
        SupportedLanguage(code: "eu", name: "euskara", englishName: "Basque"),
        SupportedLanguage(code: "ff", name: "Fulfulde", englishName: "Fulah"),
        SupportedLanguage(code: "fi", name: "suomi", englishName: "Finnish"),
        SupportedLanguage(code: "fj", name: "vosa Vakaviti", englishName: "Fijian"),
        SupportedLanguage(code: "fo", name: "føroyskt", englishName: "Faroese"),
        SupportedLanguage(code: "fr", name: "français", englishName: "French"),
        SupportedLanguage(code: "fy", name: "Frysk", englishName: "Western Frisian"),
        SupportedLanguage(code: "ga", name: "Gaeilge", englishName: "Irish"),
        SupportedLanguage(code: "gd", name: "Gàidhlig", englishName: "Scottish Gaelic; Gaelic"),
        SupportedLanguage(code: "gl", name: "Galego", englishName: "Galician"),
        SupportedLanguage(code: "gn", name: "Avañe'ẽ", englishName: "Guaraní"),
        SupportedLanguage(code: "gu", name: "ગુજરાતી", englishName: "Gujarati"),
        SupportedLanguage(code: "gv", name: "Gaelg", englishName: "Manx"),
        SupportedLanguage(code: "ha", name: "Hausa", englishName: "Hausa"),
        SupportedLanguage(code: "he", name: "עברית", englishName: "Hebrew (modern)"),
        SupportedLanguage(code: "hi", name: "हिन्दी", englishName: "Hindi"),
        SupportedLanguage(code: "ho", name: "Hiri Motu", englishName: "Hiri Motu"),
        SupportedLanguage(code: "hr", name: "hrvatski", englishName: "Croatian"),
        SupportedLanguage(code: "ht", name: "Kreyòl ayisyen", englishName: "Haitian; Haitian Creole"),
        SupportedLanguage(code: "hu", name: "Magyar", englishName: "Hungarian"),
        SupportedLanguage(code: "hy", name: "Հայերեն", englishName: "Armenian"),
        SupportedLanguage(code: "hz", name: "Otjiherero", englishName: "Herero"),
        SupportedLanguage(code: "ia", name: "Interlingua", englishName: "Interlingua"),
        SupportedLanguage(code: "id", name: "Bahasa Indonesia", englishName: "Indonesian"),
        SupportedLanguage(code: "ie", name: "Interlingue", englishName: "Interlingue"),
        SupportedLanguage(code: "ig", name: "Asụsụ Igbo", englishName: "Igbo"),
        SupportedLanguage(code: "ii", name: "ꆈꌠ꒿ Nuosuhxop", englishName: "Sichuan Yi"),
        SupportedLanguage(code: "ik", name: "Iñupiaq", englishName: "Inupiaq"),
        SupportedLanguage(code: "ina", name: "Interlingua", englishName: "Interlingua"),
        SupportedLanguage(code: "io", name: "Ido", englishName: "Ido"),
        SupportedLanguage(code: "is", name: "Íslenska", englishName: "Icelandic"),
        SupportedLanguage(code: "it", name: "Italiano", englishName: "Italian"),
        SupportedLanguage(code: "iu", name: "ᐃᓄᒃᑎᑐᑦ", englishName: "Inuktitut"),
        SupportedLanguage(code: "ja", name: "日本語", englishName: "Japanese"),
        SupportedLanguage(code: "jbo", name: "Lojban", englishName: "Lojban"),
        SupportedLanguage(code: "jv", name: "basa Jawa", englishName: "Javanese"),
        SupportedLanguage(code: "ka", name: "ქართული", englishName: "Georgian"),
        SupportedLanguage(code: "kg", name: "KiKongo", englishName: "Kongo"),
        SupportedLanguage(code: "ki", name: "Gĩkũyũ", englishName: "Kikuyu, Gikuyu"),
        SupportedLanguage(code: "kj", name: "Kuanyama", englishName: "Kwanyama, Kuanyama"),
        SupportedLanguage(code: "kk", name: "Қазақ тілі", englishName: "Kazakh"),
        SupportedLanguage(code: "kl", name: "kalaallisut", englishName: "Kalaallisut, Greenlandic"),
        SupportedLanguage(code: "km", name: "ភាសាខ្មែរ", englishName: "Central Khmer"),
        SupportedLanguage(code: "kn", name: "ಕನ್ನಡ", englishName: "Kannada"),
        SupportedLanguage(code: "ko", name: "한국어", englishName: "Korean"),
        SupportedLanguage(code: "kr", name: "Kanuri", englishName: "Kanuri"),
        SupportedLanguage(code: "ks", name: "कश्मीरी", englishName: "Kashmiri"),
        SupportedLanguage(code: "ku", name: "Kurdî", englishName: "Kurdish"),
        SupportedLanguage(code: "kv", name: "коми кыв", englishName: "Komi"),
        SupportedLanguage(code: "kw", name: "Kernewek", englishName: "Cornish"),
        SupportedLanguage(code: "ky", name: "кыргыз тили", englishName: "Kirghiz, Kyrgyz"),
        SupportedLanguage(code: "la", name: "latine", englishName: "Latin"),
        SupportedLanguage(code: "lb", name: "Lëtzebuergesch", englishName: "Luxembourgish, Letzeburgesch"),
        SupportedLanguage(code: "lg", name: "Luganda", englishName: "Ganda"),
        SupportedLanguage(code: "li", name: "Limburgs", englishName: "Limburgish, Limburgan, Limburger"),
        SupportedLanguage(code: "ln", name: "Lingála", englishName: "Lingala"),
        SupportedLanguage(code: "lo", name: "ພາສາລາວ", englishName: "Lao"),
        SupportedLanguage(code: "lt", name: "lietuvių kalba", englishName: "Lithuanian"),
        SupportedLanguage(code: "lu", name: "Tshiluba", englishName: "Luba-Katanga"),
        SupportedLanguage(code: "lv", name: "latviešu valoda", englishName: "Latvian"),
        SupportedLanguage(code: "mg", name: "Malagasy fiteny", englishName: "Malagasy"),
        SupportedLanguage(code: "mh", name: "Kajin M̧ajeļ", englishName: "Marshallese"),
        SupportedLanguage(code: "mi", name: "te reo Māori", englishName: "Māori"),
        SupportedLanguage(code: "mk", name: "македонски јазик", englishName: "Macedonian"),
        SupportedLanguage(code: "ml", name: "മലയാളം", englishName: "Malayalam"),
        SupportedLanguage(code: "mn", name: "монгол", englishName: "Mongolian"),
        SupportedLanguage(code: "mr", name: "मराठी", englishName: "Marathi (Marāṭhī)"),
        SupportedLanguage(code: "ms", name: "bahasa Melayu", englishName: "Malay"),
        SupportedLanguage(code: "mt", name: "Malti", englishName: "Maltese"),
        SupportedLanguage(code: "my", name: "ဗမာစာ", englishName: "Burmese"),
        SupportedLanguage(code: "na", name: "Ekakairũ Naoero", englishName: "Nauru"),
        SupportedLanguage(code: "nb", name: "Norsk bokmål", englishName: "Norwegian Bokmål"),
        SupportedLanguage(code: "nd", name: "isiNdebele", englishName: "North Ndebele"),
        SupportedLanguage(code: "ne", name: "नेपाली", englishName: "Nepali"),
        SupportedLanguage(code: "ng", name: "Owambo", englishName: "Ndonga"),
        SupportedLanguage(code: "nl", name: "Nederlands", englishName: "Dutch"),
        SupportedLanguage(code: "nn", name: "Norsk nynorsk", englishName: "Norwegian Nynorsk"),
        SupportedLanguage(code: "no", name: "Norsk", englishName: "Norwegian"),
        SupportedLanguage(code: "nr", name: "isiNdebele", englishName: "South Ndebele"),
        SupportedLanguage(code: "nv", name: "Diné bizaad", englishName: "Navajo, Navaho"),
        SupportedLanguage(code: "nvi", name: "Na'vi", englishName: "Na'vi"),
        SupportedLanguage(code: "ny", name: "chiCheŵa", englishName: "Chichewa; Chewa; Nyanja"),
        SupportedLanguage(code: "oc", name: "Occitan", englishName: "Occitan"),
        SupportedLanguage(code: "oj", name: "ᐊᓂᔑᓈᐯᒧᐎᓐ", englishName: "Ojibwe, Ojibwa"),
        SupportedLanguage(code: "om", name: "Afaan Oromoo", englishName: "Oromo"),
        SupportedLanguage(code: "or", name: "ଓଡ଼ିଆ", englishName: "Oriya"),
        SupportedLanguage(code: "os", name: "ирон æвзаг", englishName: "Ossetian, Ossetic"),
        SupportedLanguage(code: "pa", name: "ਪੰਜਾਬੀ", englishName: "Panjabi, Punjabi"),
        SupportedLanguage(code: "pi", name: "पाऴि", englishName: "Pāli"),
        SupportedLanguage(code: "pl", name: "polski", englishName: "Polish"),
        SupportedLanguage(code: "ps", name: "پښتو", englishName: "Pashto, Pushto"),
        SupportedLanguage(code: "pt", name: "Português", englishName: "Portuguese"),
        SupportedLanguage(code: "qu", name: "Runa Simi", englishName: "Quechua"),
        SupportedLanguage(code: "qya", name: "Quenya", englishName: "Quenya"),
        SupportedLanguage(code: "rm", name: "rumantsch grischun", englishName: "Romansh"),
        SupportedLanguage(code: "rn", name: "Ikirundi", englishName: "Rundi"),
        SupportedLanguage(code: "ro", name: "română", englishName: "Romanian, Moldavian, Moldovan"),
        SupportedLanguage(code: "ru", name: "русский язык", englishName: "Russian"),
        SupportedLanguage(code: "rw", name: "Ikinyarwanda", englishName: "Kinyarwanda"),
        SupportedLanguage(code: "sa", name: "संस्कृतम्", englishName: "Sanskrit (Saṁskṛta)"),
        SupportedLanguage(code: "sc", name: "sardu", englishName: "Sardinian"),
        SupportedLanguage(code: "sd", name: "सिन्धी", englishName: "Sindhi"),
        SupportedLanguage(code: "se", name: "Davvisámegiella", englishName: "Northern Sami"),
        SupportedLanguage(code: "sg", name: "yângâ tî sängö", englishName: "Sango"),
        SupportedLanguage(code: "si", name: "සිංහල", englishName: "Sinhala, Sinhalese"),
        SupportedLanguage(code: "sjn", name: "Sindarin", englishName: "Sindarin"),
        SupportedLanguage(code: "sk", name: "slovenčina", englishName: "Slovak"),
        SupportedLanguage(code: "sl", name: "slovenščina", englishName: "Slovenian"),
        SupportedLanguage(code: "sm", name: "gagana faa Samoa", englishName: "Samoan"),
        SupportedLanguage(code: "sn", name: "chiShona", englishName: "Shona"),
        SupportedLanguage(code: "so", name: "Soomaaliga", englishName: "Somali"),
        SupportedLanguage(code: "sq", name: "Shqip", englishName: "Albanian"),
        SupportedLanguage(code: "sr", name: "српски језик", englishName: "Serbian"),
        SupportedLanguage(code: "ss", name: "SiSwati", englishName: "Swati"),
        SupportedLanguage(code: "st", name: "Sesotho", englishName: "Southern Sotho"),
        SupportedLanguage(code: "su", name: "Basa Sunda", englishName: "Sundanese"),
        SupportedLanguage(code: "sv", name: "svenska", englishName: "Swedish"),
        SupportedLanguage(code: "sw", name: "Kiswahili", englishName: "Swahili"),
        SupportedLanguage(code: "ta", name: "தமிழ்", englishName: "Tamil"),
        SupportedLanguage(code: "te", name: "తెలుగు", englishName: "Telugu"),
        SupportedLanguage(code: "tg", name: "тоҷикӣ", englishName: "Tajik"),
        SupportedLanguage(code: "th", name: "ไทย", englishName: "Thai"),
        SupportedLanguage(code: "ti", name: "ትግርኛ", englishName: "Tigrinya"),
        SupportedLanguage(code: "tk", name: "Türkmen", englishName: "Turkmen"),
        SupportedLanguage(code: "tl", name: "Wikang Tagalog", englishName: "Tagalog"),
        SupportedLanguage(code: "tlh", name: "tlhIngan Hol", englishName: "Klingon"),
        SupportedLanguage(code: "tn", name: "Setswana", englishName: "Tswana"),
        SupportedLanguage(code: "to", name: "faka Tonga", englishName: "Tonga (Tonga Islands)"),
        SupportedLanguage(code: "tok", name: "Toki Pona", englishName: "Toki Pona"),
        SupportedLanguage(code: "tr", name: "Türkçe", englishName: "Turkish"),
        SupportedLanguage(code: "ts", name: "Xitsonga", englishName: "Tsonga"),
        SupportedLanguage(code: "tt", name: "татарча", englishName: "Tatar"),
        SupportedLanguage(code: "tw", name: "Twi", englishName: "Twi"),
        SupportedLanguage(code: "ty", name: "Reo Tahiti", englishName: "Tahitian"),
        SupportedLanguage(code: "ug", name: "Uyƣurqə", englishName: "Uighur, Uyghur"),
        SupportedLanguage(code: "uk", name: "українська", englishName: "Ukrainian"),
        SupportedLanguage(code: "ur", name: "اردو", englishName: "Urdu"),
        SupportedLanguage(code: "uz", name: "Oʻzbek", englishName: "Uzbek"),
        SupportedLanguage(code: "ve", name: "Tshivenḓa", englishName: "Venda"),
        SupportedLanguage(code: "vi", name: "Tiếng Việt", englishName: "Vietnamese"),
        SupportedLanguage(code: "vly", name: "Valyrian", englishName: "Valyrian"),
        SupportedLanguage(code: "vo", name: "Volapük", englishName: "Volapük"),
        SupportedLanguage(code: "wa", name: "Walon", englishName: "Walloon"),
        SupportedLanguage(code: "wo", name: "Wollof", englishName: "Wolof"),
        SupportedLanguage(code: "xh", name: "isiXhosa", englishName: "Xhosa"),
        SupportedLanguage(code: "yi", name: "ייִדיש", englishName: "Yiddish"),
        SupportedLanguage(code: "yo", name: "Yorùbá", englishName: "Yoruba"),
        SupportedLanguage(code: "za", name: "Saɯ cueŋƅ", englishName: "Zhuang, Chuang"),
        SupportedLanguage(code: "zh", name: "中文", englishName: "Chinese"),
        SupportedLanguage(code: "zu", name: "isiZulu", englishName: "Zulu")
    ]
}
